apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: bcheck-api-server
  namespace: bcheck-mesh-ns
spec:
  awsName: bcheck-api-server-virtual-node
  podSelector:
    matchLabels:
      app: bcheck-api-server
  listeners:
    - portMapping:
        port: 7777
        protocol: http
  serviceDiscovery:
    dns:
      hostname: bcheck-api-server.bcheck-mesh-ns.svc.cluster.local
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  namespace: bcheck-mesh-ns
  name: bcheck-api-server
spec:
  awsName: bcheck-apiserver-virtual-router
  listeners:
    - portMapping:
        port: 7777
        protocol: http
  routes:
    - name: route-to-bcheck-apiserver
      httpRoute:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeRef:
                name: bcheck-api-server
              weight: 1
        retryPolicy:
          maxRetries: 2
          perRetryTimeout:
            unit: ms
            value: 2000
          httpRetryEvents:
            - server-error
            - client-error
            - gateway-error
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: bcheck-api-server
  namespace: bcheck-mesh-ns
spec:
  awsName: bcheck-api-server.bcheck-mesh-ns.svc.cluster.local
  provider:
    virtualRouter:
      virtualRouterRef:
        name: bcheck-api-server