apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualGateway
metadata:
  name: bcheck-gateway
  namespace: bcheck-mesh-ns
spec:
  namespaceSelector:
    matchLabels:
      gateway: bcheck-gateway
  podSelector:
    matchLabels:
      app: bcheck-gateway
  gatewayRouteSelector:
    matchLabels:
      gateway: bcheck-gatewayroute
  listeners:
    - portMapping:
        port: 8000
        protocol: http
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: GatewayRoute
metadata:
  name: bcheck-gatewayroute
  namespace: bcheck-mesh-ns
  labels:
    gateway: bcheck-gatewayroute
spec:
  httpRoute:
    match:
      prefix: "/"
    action:
      target:
        virtualService:
          virtualServiceRef:
            name: bcheck-gatewayserver